#spring:
#    datasource:
#        name: test
#        url: jdbc:mysql://192.168.105.28:3306/foxconn_rick_control?useTimezone=true&serverTimezone=GMT
#        username: devapp
#        password: DEvasdfyuio
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
#mybatis:
#    #mapper interface packages
#    mapperLocations: classpath*:/mapper/**/*.xml
#    typeAliasesPackage: com.cason.demo.model